# integration tests for rstest ecosystem - run from pr comments
name: rstest-ecosystem-ci-from-commit

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

on:
  workflow_dispatch:
    inputs:
      commitSHA:
        description: "commit sha"
        required: true
        type: string
      repo:
        description: "rstest repository to use"
        required: true
        type: string
        default: "web-infra-dev/rstest"
      suite:
        description: "testsuite to run. runs all test suites when `-`."
        required: false
        type: choice
        options:
          - "-"
          # - plugins
          - rspress
          - rslib
          - rsbuild
          - rsdoctor
          - modernjs
          # - examples
      suiteRefType:
        description: "type of suite ref to use"
        required: true
        type: choice
        options:
          - precoded
          - branch
          - tag
          - commit
        default: "precoded"
      suiteRef:
        description: "suite ref to use"
        required: true
        type: string
        default: "precoded"
      updateComment:
        description: "update comment"
        required: false
        type: boolean
        default: false

jobs:
  execute-selected-suite:
    runs-on: ubuntu-latest
    if: "inputs.suite != '-'"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-rstest
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.commitSHA }}
      - run: pnpm i --frozen-lockfile
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3
      - run: >-
          pnpm tsx ecosystem-ci.ts
          run-suites
          --stack rstest
          --suite-${{ inputs.suiteRefType }} ${{ inputs.suiteRef }}
          ${{ inputs.suite }}

  execute-all:
    if: "inputs.suite == '-'"
    strategy:
      matrix:
        include:
          - suite: modernjs
            os: ubuntu-latest
          # - suite: plugins
          #   os: ubuntu-latest
          - suite: rspress
            os: ubuntu-latest
          - suite: rsbuild
            os: ubuntu-latest
          - suite: rslib
            os: ubuntu-latest
          - suite: rsdoctor
            os: ubuntu-latest
          # - suite: examples
          #   os: ubuntu-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: execute-all (${{ matrix.suite }})
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-rstest
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.commitSHA }}
      - run: pnpm i --frozen-lockfile
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3
      - run: >-
          pnpm tsx ecosystem-ci.ts
          run-suites
          --stack rstest
          ${{ matrix.suite }}
